name = "NHC"
author = "mining_also_crafting"
version = "1.0.0-1.21.1"
description = "Allows for full participation on the NotHermitCraft server. Gives extra functionality during events."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73166589b07dea63ebcf8e13aa5807cf46ffbcaa9a1bc6f4674151d226842aa4"

[versions]
fabric = "0.16.8"
minecraft = "1.21"
